<a href="https://colab.research.google.com/github/alekhya571/amritaHealthCare/blob/main/20109_FDS_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1
sets={"aman","222",11,22}
tup = tuple(sets)
print(tup)

('222', 11, 22, 'aman')


In [ ]:
#2
dictn = {"Rollno":"CB.EN.U4CSE20109", "First Name": "Arvapalli", "Last Name": "Alekhya", "DOB":"29/05/2003"}
print(dictn)

{'Rollno': 'CB.EN.U4CSE20109', 'First Name': 'Arvapalli', 'Last Name': 'Alekhya', 'DOB': '29/05/2003'}


In [ ]:
#3
import numpy as np
np.random.seed(2)
r= np.random.rand(3,5)
print(r)

[[0.4359949  0.02592623 0.54966248 0.43532239 0.4203678 ]
 [0.33033482 0.20464863 0.61927097 0.29965467 0.26682728]
 [0.62113383 0.52914209 0.13457995 0.51357812 0.18443987]]


In [ ]:
#4
import random
n = random.uniform(0.0,1.0)
print(n)
print(abs(-1234))

0.015847980987949484
1234


In [ ]:
#5
import random
n = random.randint(20,90)
print(n)

60


In [ ]:
#6
import random
import numpy as np
l = [11, 12, 13,14, 15]
print(random.sample(l, 3)) #unique elements
random.shuffle(l)
print(l)
print(np.random.choice(l,1)) #may repeat

[12, 13, 14]
[15, 11, 12, 14, 13]
[14]


In [ ]:
#7
file1 = open("MyFile.txt","w")
str1= "The King is Dead, Long Live The King" 
file1.write(str1)
file1.close()
file1 = open("MyFile.txt","r")
print(file1.read())
file1.close()

The King is Dead, Long Live The King


In [ ]:
#8
pass_score = 50
my_score = 70
if my_score>pass_score:
  print("You have passed exam")
  print("Congratulations!!")
else:
  print("You have failed exam")
  print("Better luck next time!!")

You have passed exam
Congratulations!!


In [ ]:
#9
str_1 = "The King is Dead, Long Live The King" 
print(str_1)
print(str_1[0])
print(str_1[2:6])
print(str_1[2:])
print(str_1.split())

The King is Dead, Long Live The King
T
e Ki
e King is Dead, Long Live The King
['The', 'King', 'is', 'Dead,', 'Long', 'Live', 'The', 'King']


In [12]:
#10
import numpy as np
arr = np.array([1,4,5,8])
print(arr[0:1],arr[1:2])

[1] [4]


In [17]:
#11
arr = [[1,2,3],[4,5,6]]
print(arr)

[[1, 2, 3], [4, 5, 6]]


In [16]:
#12
arr = [[1,2,3],[4,5,6]]
print(arr)
print(arr[1:])
for i in arr:
  print(i[1:])
print(len(arr))

[[1, 2, 3], [4, 5, 6]]
[[4, 5, 6]]
[2, 3]
[5, 6]
2


In [ ]:
#13
x=np.array([1,2,3,4,5,6,7,8,9,10])
x.shape=(2,5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
#14
list_1=[1,2,3]
x=np.array(list_1)
print(x)

[1 2 3]


In [ ]:
#15
arr = np.array([1,2,3])
arr.fill(9)
print(arr)

[9 9 9]


In [ ]:
#16
arr = np.array([2,4,5])
print("Sum of all elements in array:")
print(np.sum(arr))

Sum of all elements in array:
11


In [ ]:
#17
arr = np.array([2,4,5])
print("Product of all elements in array:")
print(np.prod(arr))

Product of all elements in array:
40


In [2]:
#18
import numpy as np
arr=np.array([2,1,9,1,2,22,1,1,4,55,6,2,56])
print(np.mean(arr),np.var(arr),np.amax(arr),np.amin(arr),np.argmin(arr),np.argmax(arr),np.median(arr),np.std(arr))

12.461538461538462 367.32544378698225 56 1 1 12 2.0 19.165736192147232


In [3]:
#19
arr = np.array([1, 1, 4, 5, 5, 5, 7] )
print(np.unique(arr))

[1 4 5 7]


In [4]:
#20
arr1 = np.array([1, 2, 3])
arr2 = np.array([0, 1, 1])
print(np.dot(arr1,arr2))

5


In [9]:
#21
mat = np.array([[2, 2, 4], 
              [1, 3, 5],
              [2, 3, 4]])
evalues, evectors = np.linalg.eig(mat)
print("Eigen Values: ", evalues)
print("Eigen Vectors: ", evectors)

Eigen Values:  [ 8.80916362  0.92620912 -0.73537273]
Eigen Vectors:  [[-0.52799324 -0.77557092 -0.36272811]
 [-0.604391    0.62277013 -0.7103262 ]
 [-0.59660259 -0.10318482  0.60321224]]


In [10]:
#22
x_sim = np.array([11, 22, 11, 31])
y_sim = np.array([25, 33, 31, 28])
my_rho = np.corrcoef(x_sim, y_sim)

print(my_rho)

[[1.         0.15997968]
 [0.15997968 1.        ]]
